export const en = {
  // Navigation
  nav: {
    dashboard: 'Dashboard',
    profile: 'Profile',
    settings: 'Settings',
    orders: 'Orders',
    menu: 'Menu',
    analytics: 'Analytics',
    orderManagement: 'Order Management',
    tableManagement: 'Table Management',
    newOrder: 'New Order'
  },

  // Authentication
  auth: {
    login: 'Sign In',
    logout: 'Logout',
    signingOut: 'Signing out...',
    email: 'Email Address',
    password: 'Password',
    role: 'Role',
    waiter: 'Waiter',
    admin: 'Administrator',
    signingIn: 'Signing in...',
    quickAccess: 'Quick Access',
    devMode: 'Development Mode',
    manualLogin: 'Or sign in manually',
    invalidCredentials: 'Invalid credentials or role mismatch. Please check your email, password, and role.',
    unexpectedError: 'An unexpected error occurred. Please try again.',
    fillAllFields: 'Please fill in all fields',
    demoLoginFailed: 'Demo login failed. Please check that the demo accounts are set up in Supabase.',
    player1Waiter: 'Player 1 (Waiter)',
    player2Waiter: 'Player 2 (Waiter)',
    accessWaiterDashboard: 'Access waiter dashboard',
    fullAdminAccess: 'Full admin dashboard access',
    alternativeWaiterAccount: 'Alternative waiter account',
    usingSupabaseAuth: 'Using actual Supabase authentication with demo accounts',
    ensureDemoAccounts: 'Ensure demo accounts are created in your Supabase project',
    developmentTools: 'Development Tools & Credentials',
    consoleCommands: 'Console Commands:',
    switchToAdmin: 'Switch to Admin',
    switchToPlayer1: 'Switch to Player 1',
    switchToPlayer2: 'Switch to Player 2',
    demoAccountsNote: 'Note: Demo accounts must exist in your Supabase Auth and users table',
    // Code-based authentication
    enterCode: 'Enter Code',
    accessCode: 'Access Code',
    invalidCode: 'Invalid access code. Please try again.',
    codeRequired: 'Please enter an access code',
    codePlaceholder: 'Enter your access code',
    codeInstructions: 'Enter your assigned access code to sign in to the system'
  },

  // Profile Page
  profile: {
    title: 'Profile',
    settings: 'Settings',
    subtitle: 'Manage your account settings and preferences',
    personalInfo: 'Personal Information',
    accountSettings: 'Account Settings',
    accountActions: 'Account Actions',
    appearance: 'Appearance',
    appearanceDescription: 'Customize the visual theme of your workspace',
    language: 'Language',
    languageDescription: 'Choose your preferred language for the application',
    stats: 'Personal Statistics',
    statsComingSoon: 'Stats coming soon',
    statsDescription: 'Your performance metrics and activity summary will be displayed here.',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    memberSince: 'Member Since',
    lastLogin: 'Last Login',
    saveChanges: 'Save Changes',
    changesSaved: 'Changes saved successfully!',
    errorSaving: 'Error saving changes. Please try again.',
    currentLanguage: 'Current Language',
    selectLanguage: 'Select Language',
    currentTheme: 'Current Theme',
    selectTheme: 'Select Theme',
    lightTheme: 'Light Mode',
    darkTheme: 'Dark Mode',
    lightThemeDescription: 'Clean and bright for daytime use',
    darkThemeDescription: 'Sleek and modern for low-light environments',
    themeDescription: 'Choose between light and dark themes to match your preference and environment',
    themeNote: 'Theme Preference',
    themeNoteDescription: 'Your theme choice is saved automatically and will be remembered across sessions. Both themes maintain the same professional design and functionality.',
    lightFeature1: 'Bright, airy interface',
    lightFeature2: 'High contrast text',
    lightFeature3: 'Ideal for bright environments',
    darkFeature1: 'Reduced eye strain',
    darkFeature2: 'Modern neon accents',
    darkFeature3: 'Perfect for evening use',
    signOut: 'Sign Out',
    signOutDescription: 'Sign out of your account and return to the login screen.'
  },

  // Common
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    close: 'Close',
    confirm: 'Confirm',
    tryAgain: 'Try Again',
    goHome: 'Go Home',
    noData: 'No data available',
    comingSoon: 'Coming Soon',
    actions: 'Actions',
    status: 'Status',
    name: 'Name',
    price: 'Price',
    quantity: 'Quantity',
    total: 'Total',
    add: 'Add',
    remove: 'Remove',
    update: 'Update',
    create: 'Create',
    submit: 'Submit'
  },

  // Orders
  orders: {
    title: 'Orders',
    newOrder: 'New Order',
    orderDetails: 'Order Details',
    tableNumber: 'Table Number',
    status: 'Status',
    items: 'Items',
    notes: 'Notes',
    total: 'Total',
    basePrice: 'Base Price',
    serviceFee: 'Service Fee',
    serviceFeePercent: 'Service Fee (15%)',
    createdBy: 'Created By',
    createdAt: 'Created At',
    waiter: 'Waiter',
    time: 'Time',
    summary: 'Summary',
    'in-progress': 'In Progress',
    'completed': 'Completed',
    'updated': 'Updated',
    inProgress: 'In Progress',
    completed: 'Completed',
    updated: 'Updated',
    filterByStatus: 'Filter by Status',
    statusesShown: 'statuses shown',
    markCompleted: 'Mark as Completed',
    editOrder: 'Edit Order',
    deleteOrder: 'Delete Order',
    orderCreated: 'Order created successfully!',
    orderUpdated: 'Order updated successfully!',
    orderDeleted: 'Order deleted successfully!',
    confirmDelete: 'Are you sure you want to delete this order? This action cannot be undone.',
    noOrders: 'No orders found',
    ordersDescription: 'Orders will appear here when created',
    selectTable: 'Select Table',
    selectMenuItems: 'Menu',
    selectedItems: 'Selected Items',
    orderInfo: 'Order Information',
    specialInstructions: 'Special instructions or notes...',
    createOrder: 'Create Order',
    updateOrder: 'Update Order',
    addItems: 'Add Items',
    removeItem: 'Remove Item',
    updateQuantity: 'Update Quantity',
    selectMenuItem: 'Select menu item...',
    addItem: 'Add Item',
    orderMustHaveItems: 'Order must have at least one item',
    tableNumberRequired: 'Table number is required',
    updatedPricing: 'Updated Pricing',
    originalWaiter: 'Original Waiter',
    orderInformation: 'Order Information',
    currentItems: 'Order Items',
    pricingDetails: 'Pricing Details',
    adminNote: 'Admin Note: You can modify all aspects of this order including table number, status, notes, and items. Changes will be saved immediately and reflected across the system.',
    waiterNote: 'Note: Saving changes will automatically update the order status to "Updated" and recalculate the pricing based on current menu prices.',
    saving: 'Saving...',
    showingOrders: 'Showing',
    ofOrders: 'of',
    ordersText: 'orders',
    orderID: 'Order ID',
    table: 'Table',
    viewDetails: 'View details',
    markAsCompleted: 'Mark as completed',
    done: 'Done',
    del: 'Del',
    each: 'each',
    eachPrice: 'each',
    // Table status translations
    tableAvailable: 'Available',
    tableOccupied: 'Occupied',
    tableSelected: 'Selected',
    tableOccupiedTooltip: 'Table Occupied',
    tableOccupiedError: 'This table is currently occupied. Please select a different table.',
    occupiedTablesCount: '{{count}} tables currently occupied'
  },

  // Menu
  menu: {
    title: 'Menu Management',
    description: 'Manage your restaurant menu items with full Supabase sync',
    addNewItem: 'Add New Item',
    editItem: 'Edit Menu Item',
    itemName: 'Item Name',
    price: 'Price',
    category: 'Category',
    available: 'Available for ordering',
    unavailable: 'Unavailable',
    weight: 'Weight/Quantity',
    weightOptional: 'e.g., 300гр, 2шт, 1л (optional)',
    weightDescription: 'Optional field for specifying weight, quantity, or volume',
    searchItems: 'Search menu items...',
    allCategories: 'All Categories',
    showUnavailable: 'Show unavailable items',
    itemCreated: 'Menu item created successfully!',
    itemUpdated: 'Menu item updated successfully!',
    itemDeleted: 'Menu item deleted successfully!',
    confirmDeleteItem: 'Are you sure you want to delete this menu item? This action cannot be undone.',
    noItems: 'No menu items found',
    itemsDescription: 'Try adjusting your search or filters',
    enterItemName: 'Enter item name',
    enterPrice: 'Enter price',
    realTimeSync: 'Real-time Supabase sync enabled',
    syncDescription: 'Changes will be immediately synchronized across all connected clients',
    updateItem: 'Update Item',
    addItem: 'Add Item',
    markAsUnavailable: 'Mark as unavailable',
    markAsAvailable: 'Mark as available',
    deleteItem: 'Delete item',
    editItemAction: 'Edit item',
    showingItems: 'Showing',
    ofItems: 'of',
    itemsText: 'items',
    weightQuantity: 'Weight/Quantity',
    statusAvailable: 'Available',
    statusUnavailable: 'Unavailable'
  },

  // Dashboard
  dashboard: {
    welcome: 'Welcome back',
    adminDashboard: 'Administrator',
    waiterDashboard: 'Table Management',
    totalOrders: 'Total Orders',
    totalRevenue: 'Total Revenue',
    recentActivity: 'Recent Activity',
    quickStats: 'Quick Statistics',
    manageOrders: 'Manage orders, menu, and users',
    manageOrdersEfficiently: 'Manage your orders efficiently',
    exportCSV: 'Export CSV',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    updated: 'Updated',
    orders: 'ORDERS',
    manageOrdersTab: 'MANAGE ORDERS',
    menuTab: 'MENU',
    analyticsTab: 'ANALYTICS'
  },

  // Table Management
  table: {
    tableManagement: 'Table Management',
    newOrder: 'New Order'
  },

  // Languages
  languages: {
    en: 'English',
    ru: 'Русский'
  },

  // Errors
  errors: {
    pageNotFound: 'Page Not Found',
    pageNotFoundDescription: "Oops! The page you're looking for seems to have wandered off like a waiter during rush hour. Let's get you back to where the action is.",
    somethingWentWrong: 'Something went wrong',
    unexpectedError: 'An unexpected error occurred. Please try refreshing the page or contact support if the problem persists.',
    connectionError: 'Connection Error',
    connectionErrorDescription: 'Unable to connect to the server. Please check your internet connection and try again.',
    loadingError: 'Failed to load data. Please try again.',
    savingError: 'Failed to save changes. Please try again.',
    orderNotFound: 'Order not found. This order may have been deleted by another user or no longer exists in the system.',
    needHelp: 'Need Help?',
    helpDescription: 'If you believe this is an error or you\'re having trouble navigating the Themis café management system, here are some quick links to get you back on track:',
    forWaiters: 'For Waiters',
    forAdmins: 'For Admins',
    waitersDescription: 'Manage tables and create orders',
    adminsDescription: 'Manage menu, orders, and analytics',
    validRoutes: 'Valid Routes:',
    redirectsToDashboard: 'Redirects to dashboard',
    mainDashboard: 'Main dashboard (role-based)',
    loginPage: 'Login page (bypassed in dev mode)',
    debugInfo: 'Debug Info',
    requestedPath: 'Requested path:',
    legitimateError: 'This is a legitimate 404 error for an unmatched route.',
    backToDashboard: 'Back to Dashboard',
    goBack: 'Go Back'
  },

  // Categories (for menu)
  categories: {
    'ЗАВТРАКИ': 'BREAKFAST',
    'САЛАТЫ': 'SALADS',
    'ПЕРВЫЕ БЛЮДА': 'FIRST COURSES',
    'ВТОРЫЕ БЛЮДА': 'MAIN COURSES',
    'НАЦИОНАЛЬНАЯ КУХНЯ': 'NATIONAL CUISINE',
    'ГАРНИРЫ': 'SIDE DISHES',
    'БАР': 'BAR',
    'ШАШЛЫКИ': 'GRILLED',
    'БЛЮДА НА КОМПАНИЮ': 'GROUP DISHES',
    'ФАСТФУД': 'FAST FOOD'
  }
};